cat('INTIATING PROJECT-KARENINA PIPELINE\n\n')
prmtrs <- readLines('parameters.R')
cat(paste0(prmtrs, collapse='\n'))
cat('\n\n################################################\n')
source(file.path('stages', '1_pin.R'), local=TRUE)
cat('\n\n################################################\n')
source(file.path('stages', '2_slice.R'), local=TRUE)
cat('\n\n################################################\n')
source(file.path('stages', '3_wrngl.R'), local=TRUE)
cat('\n\n################################################\n')